Add a datamodel store to the frontend
Kreiswasserwacht-Wurzburg/digitales_wachbuch pull request #38
Opened 2024-02-18 17:38 UTC by pwueje

By using a store for our datamodels, we  can decrease the coupling between data retrieval and data presentation. This enhances furthermore the ability to create views, without the necessity of knowing how to get the data. This makes it even easier for non-developers to work on the views. Furthermore it is easier to switch between different API implementations.

Another advantage is, that the complete data retrieval logic is on one point.

Closes Issue-37

2024-02-18 18:43 UTC, mawux requested changes

2024-02-18 18:43 UTC, mawux commented on digital-guardbook-ui/src/components/sentry/SentryDisplay.vue
>                      </template>
Move button (line 75 to line 77) out of template tag. otherwise it is not possible to use it if there is no registration time set.

2024-02-20 20:05 UTC, pwueje commented on digital-guardbook-ui/src/components/sentry/SentryDisplay.vue
>                      </template>
I moved it outside with an `else`. Nevertheless, this should be fixed with #36

2024-02-24 20:48 UTC, mawux approved these changes, later dismissed

2024-02-25 12:03 UTC, merged